### ISSUE TITLE
Output to stdout instead of stderr

### ISSUE THREAD

**Issue by fkjensen** [humio/cli#71] opened 2021-03-24 11:46 UTC

**Comment by fkjensen** [comment] 2021-03-24 11:50
Using humioctl 0.28.2 the output seems to be directed to stderr instead of expected stdout. I had to do a redirect of stderr to do grep on the output of humioctl. I tested both groups and users commands; I think this is a general issue.

humioctl -u titaniumcluster users list 2>&1 | grep -E '(bigcorp.com|another.com)'

**Comment by SaaldjorMike** [comment] 2022-01-04 13:27
This sounds like a duplicate of https://github.com/humio/cli/issues/50.
Perhaps give my comment here a read: https://github.com/humio/cli/issues/50#issuecomment-1004809570

**Closed by SaaldjorMike** 2022-01-04 13:27 UTC
